spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.151.83:3306/book?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  #  redis:
  #    host: localhost
  #    password: root
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8000

logging:
  level:
    com.book.management: debug
    org.springframework: info

mybatis:
  mapper-locations: classpath:mappers/*.xml
  map-underscore-to-camel-case: true # 重要,支持驼峰写法,要不会返回null
  type-aliases-package: com.book.management.mybatis.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: false   # 禁用合理化时，会返回空数据
  support-methods-arguments: true
  params: count=countSql
